Use JSON instead of YAML
mgxd/nipype-regtests pull request #12
Opened 2017-04-09 19:04 UTC by kaczmarj

Addresses #9

2017-04-09 19:13 UTC, kaczmarj commented
Build raises `APIError: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.26, server API version: 1.24)")`. This is fixed by ab328ab70592c6e7f7d95445f8b1ce1612a58a3a in PR #10 .

Pytest passes on my local machine when running `python -m pytest /Users/jakubkaczmarzyk/Projects/nipype-regtests/src/`.

2017-04-10 19:36 UTC, mgxd commented
rebuilding - will merge once passing

2017-04-10 20:19 UTC, mgxd requested changes

2017-04-10 20:19 UTC, mgxd commented on samples/ubuntu-16.04_py-3.5.1/Dockerfile
> +ENV PATH=/usr/local/miniconda/envs/new_env/bin:$PATH
new line

2017-04-10 20:19 UTC, mgxd commented on samples/ubuntu-16.04_py-3.5.1/conda-env.json
> +}
again

2017-04-10 20:19 UTC, mgxd commented on src/utils.py
> +        json.dump(obj, fp, indent=4)
more flexible to define indent in arguments with a default of 4

2017-04-10 20:39 UTC, kaczmarj commented on samples/ubuntu-16.04_py-3.5.1/conda-env.json
> +}
This JSON was created with `src.utils.save_json()`. I updated that function to add a newline at the end of the file.

2017-04-10 20:39 UTC, kaczmarj commented on samples/ubuntu-16.04_py-3.5.1/Dockerfile
> +ENV PATH=/usr/local/miniconda/envs/new_env/bin:$PATH
I'll keep this in mind when I update the class that creates the Dockerfile.

2017-04-10 20:40 UTC, mgxd approved these changes

2017-04-10 20:41 UTC, merged